name: Update animated terminal

on:
  workflow_dispatch:
  schedule:
    - cron:  0 1,5,9,13,17,21 * * *
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: AceKiron/actions@generate-profile-terminal
        with:
          username: "AceKiron"
          output-path: "./assets/animated-terminal.gif"
          country: "Netherlands"
          website: "https://acekiron.github.io/"
          pronouns: "They/them"
        env:
          GITHUB_TOKEN: ${{ github.token }}

#       - uses: AceKiron/actions@push-to-repository
#         with:
#           files: "*"
#           message: "Animated terminal updated"
#           branch: "main"

#       - run: |
#           git add assets/animated-terminal.gif
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git commit -m "Animated terminal updated" -a --allow-empty
#           git push origin main
