name: Update animated terminal

on:
  workflow_dispatch:
  schedule:
    - cron:  0 1,5,9,13,17,21 * * *
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: AceKiron/actions@generate-profile-terminal
        with:
          username: "AceKiron"
          output-path: "./assets/animated-terminal.gif"
          country: "Netherlands"
          website: "https://acekiron.github.io/"
          pronouns: "They/them"
        env:
          GITHUB_TOKEN: ${{ github.token }}

#       - run: mkdir -p assets

#       - name: Setup Node.js 16.x
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16.x
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm i
      
#       - run: node scripts/animated-terminal.js
#         env:
#           GH_API_KEY: ${{secrets.GH_API_KEY}}

#       - run: ls -R

#       - run: |
#           git add assets/animated-terminal.gif
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git commit -m "Animated terminal updated" -a --allow-empty
#           git push origin main
